SELECT NAME, COALESCE(
(SELECT COUNT(*) FROM photoflow.PHOTO_POST
JOIN photoflow.USER ON USER.USER_ID = PHOTO_POST.USER_ID
WHERE DAY(PHOTO_POST.CREATED_AT) = 9
AND MONTH(PHOTO_POST.CREATED_AT) = 5
AND PHOTO_POST.USER_ID = usersTable.USER_ID ), 0) as 'Num of posts'
FROM photoflow.PHOTO_POST
RIGHT JOIN photoflow.USER as usersTable ON usersTable.USER_ID = PHOTO_POST.USER_ID
GROUP BY usersTable.USER_ID;